from . import fleet_vehicle
from . import res_partner
from . import sa_delivery_partner
from . import sa_delivery_settings
from . import sa_delivery_shop
from . import fleet_dispatch
from . import stock_picking
from . import notifications
from . import sa_fleet_position
from . import sa_fleet_map
from . import sa_rider_rpc
from . import sa_rider_rpc_trip
